In [1]:
import pandas as pd
import numpy as np

In [2]:
listings_data = pd.read_csv('listings.csv.gz')

In [3]:
listings_data

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,10080,https://www.airbnb.com/rooms/10080,20210412154228,2021-04-13,D1 - Million Dollar View 2 BR,"Stunning two bedroom, two bathroom apartment. ...",NaN,https://a0.muscache.com/pictures/55778229/c2f7...,30899,https://www.airbnb.com/users/show/30899,...,9.0,10.0,9.0,18-476608,f,40,40,0,0,0.14
1,13358,https://www.airbnb.com/rooms/13358,20210412154228,2021-04-13,Monthly (or Longer ) Designer One Bedroom Down...,<b>The space</b><br />This suites central loca...,NaN,https://a0.muscache.com/pictures/c23bb7ef-e300...,52116,https://www.airbnb.com/users/show/52116,...,10.0,10.0,9.0,18-611603,f,1,1,0,0,3.27
2,13490,https://www.airbnb.com/rooms/13490,20210412154228,2021-04-13,Vancouver's best kept secret,This apartment rents for one month blocks of t...,"In the heart of Vancouver, this apartment has ...",https://a0.muscache.com/pictures/73394727/79d5...,52467,https://www.airbnb.com/users/show/52467,...,10.0,10.0,10.0,NaN,f,1,1,0,0,0.73
3,14267,https://www.airbnb.com/rooms/14267,20210412154228,2021-04-13,EcoLoft Vancouver,"The Ecoloft is located in the lovely, family r...",We live in the centre of the city of Vancouver...,https://a0.muscache.com/pictures/3646de9b-934e...,56030,https://www.airbnb.com/users/show/56030,...,9.0,10.0,9.0,21-156500,t,1,1,0,0,0.26
4,16254,https://www.airbnb.com/rooms/16254,20210412154228,2021-04-12,Close to PNE/Hastings Park and East Village,2 Bedroom garden level guest suite.(lower leve...,"Good Eats, Cute Shops and all the personality ...",https://a0.muscache.com/pictures/90623667/583c...,63238,https://www.airbnb.com/users/show/63238,...,10.0,10.0,9.0,19-162421,t,1,1,0,0,0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4294,49132295,https://www.airbnb.com/rooms/49132295,20210412154228,2021-04-13,Luxurious 3 Bedroom Unit With English Bay Views!,"Stunning large, modern, brand-new 3 bedroom an...",NaN,https://a0.muscache.com/pictures/d5f23f5b-f10b...,219146817,https://www.airbnb.com/users/show/219146817,...,NaN,NaN,NaN,NaN,f,5,5,0,0,NaN
4295,49138797,https://www.airbnb.com/rooms/49138797,20210412154228,2021-04-13,19-9-10 Private room,Private room in a new house with shared bathro...,NaN,https://a0.muscache.com/pictures/02048308-7b1f...,356993612,https://www.airbnb.com/users/show/356993612,...,NaN,NaN,NaN,21-107408,f,14,1,13,0,NaN
4296,49146266,https://www.airbnb.com/rooms/49146266,20210412154228,2021-04-13,Prime Coal harbour | Luxury Finishings,Welcome to this beautiful fully furnished Prim...,"Location, Location, Location! Steps from the S...",https://a0.muscache.com/pictures/ee697899-6185...,396405989,https://www.airbnb.com/users/show/396405989,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
4297,49148812,https://www.airbnb.com/rooms/49148812,20210412154228,2021-04-13,DT- Ocean View 1BD w/ Private Bathroom Kitchen...,Private one bedroom suite apartment in heart o...,"Heart of Downtown Vancouver , walking distance...",https://a0.muscache.com/pictures/02a2a9da-68e0...,88405999,https://www.airbnb.com/users/show/88405999,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
4298,49153995,https://www.airbnb.com/rooms/49153995,20210412154228,2021-04-13,New! High end clean condo downtown!,Incredible quiet and cozy high floor view suit...,Walk score 100%<br />Near everything downtown<...,https://a0.muscache.com/pictures/b0c385f0-c4b5...,188731233,https://www.airbnb.com/users/show/188731233,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN

In [4]:
listings_data.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
       'neighborhood_overview', 'picture_url', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [5]:
col = ['last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value']

In [6]:
lis = listings_data[col]

In [7]:
lis

,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,2017-02-26,93.0,9.0,9.0,10.0,9.0,10.0,9.0
1,2021-01-01,93.0,9.0,10.0,9.0,10.0,10.0,9.0
2,2020-10-31,98.0,10.0,10.0,10.0,10.0,10.0,10.0
3,2020-02-07,95.0,10.0,9.0,10.0,9.0,10.0,9.0
4,2019-08-19,96.0,10.0,10.0,10.0,10.0,10.0,9.0
...,...,...,...,...,...,...,...,...
4294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
lis["review_scores_rating"].isna().sum()

825

In [9]:
columns_needed = ['id', 'listing_url', 'name', 'description', 'picture_url', 'latitude', 'longitude', 'property_type', 'accommodates', 'bedrooms', 'beds', 'amenities', 'price' ]

In [10]:
listings_data = listings_data[columns_needed]

In [11]:
listings_data

,id,listing_url,name,description,picture_url,latitude,longitude,property_type,accommodates,bedrooms,beds,amenities,price
0,10080,https://www.airbnb.com/rooms/10080,D1 - Million Dollar View 2 BR,"Stunning two bedroom, two bathroom apartment. ...",https://a0.muscache.com/pictures/55778229/c2f7...,49.28872,-123.12046,Entire condominium,5,2.0,2.0,"[""Iron"", ""Dryer"", ""Bed linens"", ""Cooking basic...",$150.00
1,13358,https://www.airbnb.com/rooms/13358,Monthly (or Longer ) Designer One Bedroom Down...,<b>The space</b><br />This suites central loca...,https://a0.muscache.com/pictures/c23bb7ef-e300...,49.28201,-123.12669,Entire condominium,2,1.0,1.0,"[""Iron"", ""Dryer"", ""Bed linens"", ""Cooking basic...",$85.00
2,13490,https://www.airbnb.com/rooms/13490,Vancouver's best kept secret,This apartment rents for one month blocks of t...,https://a0.muscache.com/pictures/73394727/79d5...,49.25622,-123.06607,Entire apartment,2,1.0,1.0,"[""Iron"", ""Outdoor dining area"", ""Ethernet conn...",$145.00
3,14267,https://www.airbnb.com/rooms/14267,EcoLoft Vancouver,"The Ecoloft is located in the lovely, family r...",https://a0.muscache.com/pictures/3646de9b-934e...,49.24922,-123.08139,Entire house,4,1.0,2.0,"[""Iron"", ""Dryer"", ""Cooking basics"", ""Hot water...",$140.00
4,16254,https://www.airbnb.com/rooms/16254,Close to PNE/Hastings Park and East Village,2 Bedroom garden level guest suite.(lower leve...,https://a0.muscache.com/pictures/90623667/583c...,49.27721,-123.04086,Entire guest suite,4,2.0,3.0,"[""Iron"", ""Dryer"", ""Bed linens"", ""Cooking basic...",$195.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4294,49132295,https://www.airbnb.com/rooms/49132295,Luxurious 3 Bedroom Unit With English Bay Views!,"Stunning large, modern, brand-new 3 bedroom an...",https://a0.muscache.com/pictures/d5f23f5b-f10b...,49.27391,-123.13012,Entire apartment,7,3.0,5.0,"[""Heating"", ""Essentials"", ""Kitchen"", ""Iron"", ""...",$500.00
4295,49138797,https://www.airbnb.com/rooms/49138797,19-9-10 Private room,Private room in a new house with shared bathro...,https://a0.muscache.com/pictures/02048308-7b1f...,49.25275,-123.09184,Private room in house,2,1.0,1.0,"[""Heating"", ""Kitchen"", ""Fire extinguisher"", ""D...",$38.00
4296,49146266,https://www.airbnb.com/rooms/49146266,Prime Coal harbour | Luxury Finishings,Welcome to this beautiful fully furnished Prim...,https://a0.muscache.com/pictures/ee697899-6185...,49.28631,-123.12455,Entire apartment,2,1.0,NaN,"[""Kitchen"", ""Body soap"", ""Shampoo"", ""Hot tub"",...",$160.00
4297,49148812,https://www.airbnb.com/rooms/49148812,DT- Ocean View 1BD w/ Private Bathroom Kitchen...,Private one bedroom suite apartment in heart o...,https://a0.muscache.com/pictures/02a2a9da-68e0...,49.28822,-123.13061,Entire apartment,1,1.0,1.0,"[""Dryer"", ""Bed linens"", ""Elevator"", ""Paid park...",$66.00
4298,49153995,https://www.airbnb.com/rooms/49153995,New! High end clean condo downtown!,Incredible quiet and cozy high floor view suit...,https://a0.muscache.com/pictures/b0c385f0-c4b5...,49.27849,-123.12562,Entire condominium,2,NaN,0.0,"[""Ethernet connection"", ""Hot tub"", ""Dryer"", ""B...",$73.00

In [12]:
def clean_amenities_data(amenities_data):

    #find unique amenities and the number of them to choose which are important for a traveller
    print(amenities_data['amenity'].value_counts())

    # choose important amenities to work with
    amenities_required = ['restaurent', 'fast_food', 'cafe','bank','atm','pharmacy','bicycle_rental','fuel','pub','bar','car_sharing','car_rental','clinic','doctors','hospital','ice_cream','fountain','theatre','police','bus_station']
    #adapted from : https://www.kite.com/python/answers/how-to-filter-a-pandas-dataframe-with-a-list-by-%60in%60-or-%60not-in%60-in-python
    bool_series = amenities_data.amenity.isin(amenities_required)
    filtered_amenities_df = amenities_data[bool_series]
    filtered_amenities_df.reset_index(inplace=True, drop=True)

    return filtered_amenities_df

In [13]:
amenities_data = pd.read_json('amenities-vancouver.json.gz', lines=True)
amenities_data_clean = clean_amenities_data(amenities_data)

bench              3738
restaurant         2472
bicycle_parking    1423
fast_food          1147
waste_basket       1137
                   ...
park                  1
first_aid             1
biergarten            1
gym                   1
casino                1
Name: amenity, Length: 138, dtype: int64

In [14]:
amenities_data_clean

,lat,lon,timestamp,amenity,name,tags
0,49.260812,-123.125736,2020-03-20T18:22:12.000-07:00,cafe,Starbucks,"{'brand:wikidata': 'Q37158', 'official_name': ..."
1,49.260953,-123.125704,2019-08-02T18:11:20.000-07:00,fast_food,Salad Loop,{'opening_hours': 'Mo-Fr 07:00-17:00; Sa 10:00...
2,49.264041,-123.153407,2019-08-29T18:50:05.000-07:00,fuel,Shell,"{'brand:wikidata': 'Q154950', 'addr:housenumbe..."
3,49.283192,-123.109050,2015-12-18T21:41:07.000-08:00,pub,The Cambie,"{'toilets:wheelchair': 'no', 'wheelchair': 'li..."
4,49.082281,-122.056130,2018-02-12T01:42:34.000-08:00,fuel,Petro-Canada,{'name:en': 'Petrol Canada'}
...,...,...,...,...,...,...
4456,49.264044,-123.174166,2019-09-13T13:56:49.000-07:00,cafe,Tim Hortons,"{'brand:wikidata': 'Q175106', 'addr:housenumbe..."
4457,49.263998,-123.173758,2019-06-08T06:31:22.000-07:00,fast_food,Subway,"{'brand:wikidata': 'Q244457', 'website': 'http..."
4458,49.278424,-122.806704,2013-03-26T23:45:49.000-07:00,cafe,Creekside Coffee,{}
4459,49.282666,-122.826978,2019-09-13T13:56:49.000-07:00,pub,Brown's Social House,"{'addr:housenumber': '215', 'brewery': 'Guinne..."
4460,49.282420,-122.826340,2019-09-13T13:56:49.000-07:00,cafe,Gallagher's Cafe,"{'addr:housenumber': '232', 'internet_access':..."

In [34]:
ad= amenities_data_clean.head(5)
ad

,lat,lon,timestamp,amenity,name,tags
0,49.260812,-123.125736,2020-03-20T18:22:12.000-07:00,cafe,Starbucks,"{'brand:wikidata': 'Q37158', 'official_name': ..."
1,49.260953,-123.125704,2019-08-02T18:11:20.000-07:00,fast_food,Salad Loop,{'opening_hours': 'Mo-Fr 07:00-17:00; Sa 10:00...
2,49.264041,-123.153407,2019-08-29T18:50:05.000-07:00,fuel,Shell,"{'brand:wikidata': 'Q154950', 'addr:housenumbe..."
3,49.283192,-123.109050,2015-12-18T21:41:07.000-08:00,pub,The Cambie,"{'toilets:wheelchair': 'no', 'wheelchair': 'li..."
4,49.082281,-122.056130,2018-02-12T01:42:34.000-08:00,fuel,Petro-Canada,{'name:en': 'Petrol Canada'}

In [36]:
ad[['name']] = ad[['name']].apply(lambda x: 1 if x == 'Shell' else 0)
ad

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [15]:
amenities_data_clean['amenity'].unique()

array(['cafe', 'fast_food', 'fuel', 'pub', 'pharmacy', 'doctors', 'atm',
       'bank', 'theatre', 'bar', 'car_rental', 'car_sharing',
       'bicycle_rental', 'clinic', 'ice_cream', 'fountain', 'bus_station',
       'hospital', 'police'], dtype=object)

In [16]:
amenities_required = ['restaurent', 'fast_food', 'cafe','bank','atm','pharmacy','fuel','car_rental','clinic','doctors','hospital','ice_cream','fountain','theatre']

In [19]:
amenities_required

['restaurent',
 'fast_food',
 'cafe',
 'bank',
 'atm',
 'pharmacy',
 'fuel',
 'car_rental',
 'clinic',
 'doctors',
 'hospital',
 'ice_cream',
 'fountain',
 'theatre']

In [20]:
d = dict.fromkeys(amenities_required, 0)

In [21]:
d

{'restaurent': 0,
 'fast_food': 0,
 'cafe': 0,
 'bank': 0,
 'atm': 0,
 'pharmacy': 0,
 'fuel': 0,
 'car_rental': 0,
 'clinic': 0,
 'doctors': 0,
 'hospital': 0,
 'ice_cream': 0,
 'fountain': 0,
 'theatre': 0}

In [24]:
d['fuel'] +=1

In [25]:
d

{'restaurent': 0,
 'fast_food': 0,
 'cafe': 0,
 'bank': 0,
 'atm': 0,
 'pharmacy': 0,
 'fuel': 3,
 'car_rental': 0,
 'clinic': 0,
 'doctors': 0,
 'hospital': 0,
 'ice_cream': 0,
 'fountain': 0,
 'theatre': 0}

In [ ]:
def haversine_distance(lon1, lat1, lon2, lat2):
    # convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])
    # haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    r = 6371 # Radius of earth in kilometers. Use 3956 for miles
    return c * r * 1000

In [32]:
# return a dictionary with number of amenities in a 1km radius of this lat and lon
def num_amenities(lat, lon, amenities_data_clean, amenities_required):
    amenities_dict = dict.fromkeys(amenities_required,0)
    
    
    
    #amenities_data_clean.apply(lambda x:amenities_dict[x['amenity']]=1 if (haversine_distance(lon, lat, x['lon'], x['lat']) <=1000))
    
    
    
    print(amenities_dict)

SyntaxError: invalid syntax (<ipython-input-32-f97d67faf92b>, line 5)